### ISSUE TITLE
workflow: being "done" with an image

### ISSUE THREAD

**Issue by ppbrown** [PMahern/StableDiffusionTagManager#10]
This is a followup to #8  reguarding
" I'm not sure what you mean by the "done with an image" functionality, do you mean you want it to advance to the next image?"

The current tag input goes against common UI experience. 
Typically, when a user gets sent to an (input text) box, they input the text, they press return.. and they are done.
But currently, if they press return.... nothing happens.  The tag input box is still active with the blinking cursor expecting typing.

This is important for TWO reasons: one is, it just feels weird from a user experience. But the other reason is that when you are done with the tag input... arrow keys then work to switch between images.

Turns out this is actually a more widespread issue. For example, the "Add tag to all images" dialog
(Which is mislabeled "Lookup tag?!?!"")
When I finish typing in the tagname, the expectation is that I press return.. and it will go add the tag.
But here again, enter does nothing. I have to manually move my hand back to the mouse and click "OK"???
Unpleasant :(

**Comment by PMahern** [comment]
I made pressing enter in the tag entry dialog basically be the same as clicking the ok button (https://github.com/PMahern/StableDiffusionTagManager/commit/d0cbe1a33f3837a7bb95fecd491d09ec986b9286), where else are you seeing this behavior? For completing an image can't you simply use the next image hotkey instead of pressing enter when you're done entering in the last tag for the image?

**Comment by ppbrown** [comment]
i dont have another specific place to raise this concern at present (although I vaguely recall there was one more place; i dont remember where :(  )

as far as "you can go to the next image"....
This is true... but it makes the UI different from what users are used to, in both windows and linux. It's just a "wrong" feeling user experience.
(and what if the user doesnt want to go to the next image?)

In this sort of situation, usually either enter, or ESC, or both, would end tag input.
When the cursor keeps blinking, it feels like "there's something more I need to do to commit this tag to the image"

**Comment by PMahern** [comment]
I already switched enter to start the next tag entry, I made pressing escape while editing a tag drop focus in this commit https://github.com/PMahern/StableDiffusionTagManager/commit/e293a0001a647a531f0b63c73af1654b1cc551be.

**Comment by ppbrown** [comment]
awesome.
the one thing I can think of, if you didnt add it already, is that pressing ESC in an empty tag entry, should cancel entry and auto-delete the tag.
Currently, that sort of thing leaves an empty tag, which is kinda wierd.

**Comment by PMahern** [comment]
Ok, added in logic to delete the tag if it's empty.
