### ISSUE TITLE
Command for activating the webui

### ISSUE THREAD

**Issue by veraburg** [PMahern/StableDiffusionTagManager#13]
Hi, very amateur coder here - could you provide the command that activates the WebUI for MacOs? I downloaded the "sdtm-osx-x64-1.0.0-beta13" folder but do not know how to start up the webui. Thanks a lot!

**Comment by PMahern** [comment]
It's not a webui, it's a desktop application, so it doesn't run in a browser or anything. The executable is the StableDiffusionTagManager file in the root of that file archive you extracted. However, it won't run unless you also remove some attributes that MacOS attaches to the executable/library files that flag the files as being "unsafe". The instructions are here: https://github.com/PMahern/StableDiffusionTagManager?tab=readme-ov-file#mac

Once you've run those commands to remove the attributes then you can launch the application by running ./StableDiffusionTagManager in a command prompt in the extracted folder. I also must caution that I have not tested the application much beyond just launching it and opening a folder on a Mac system, I've been meaning to test it more thoroughly but don't have access to a Mac system that I can feely tinker with at the moment.
