### ISSUE TITLE
Error message when running built-in natural language interrogator "The pipe has been ended"

### ISSUE THREAD

**Issue by Fylifa** [PMahern/StableDiffusionTagManager#14]
When using the natural language interrogator, joycaption, it's bringing up an error message:

![Capture](https://github.com/user-attachments/assets/d9e07f22-31ad-4584-9529-c962b7c3639c)

'Failed to interrogate the image with the selected natural language interrogator. Error message: The pipe has been ended.'

Looking in the directory it looks like it did download the files and set up a python environment for joycaption but didn't go further than that.

The other smilingwolf interrogators do work as expected (if a little slow), only getting the error on the natural language one

**Comment by PMahern** [comment]
I assume this is on Windows? I tried testing it on another Windows system I have and did run into a couple issues. I'll figure out why it works on my dev machine and not other ones and have a build out to fix it later today.

You can try to fix it yourself in the meantime, it's part of the venv setup.

The first issue is it's not installing torch with CUDA, here's how to fix it:
1. Open a command prompt and go to the "taggers\joycaption" directory and activate the venv by running:
`venv\Scripts\activate.bat`
2. Install the cuda version of pytorch by running (this assumes you have cuda 12.4 or later installed):
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124` 

The other issue is a bit more strange and may not be happening on your system, it happens on one of my windows machines and not the other (could POSSIBLE be something  to with with file path length limitations). During the venv setup for joycaption it tries to replace 
`MODEL_PATH = "meta-llama/Meta-Llama-3.1-8B"`
with
`MODEL_PATH = "unsloth/Meta-Llama-3.1-8B-bnb-4bit"`
on line 15 of the app.py file in the joycaption example repo. You'll need to make this change manually if it wasn't applied.

**Comment by Fylifa** [comment]
Hello! Sorry for not specifying before, but yes I am running on a windows machine.

I checked both issues, I started with the second one first and you were right the model path didn't get changed in app.py. Though that change alone didn't fix the problem. Got the same error.

Next I did the pytorch install and that seemed to fix it (though I had to use 11.8 instead of 12.4) 

Joycaption now works in the program! Though now it has a new issue (sorry to keep bringing more problems)

It only does now the first image with joycaption instead of all of them and doing 'interrogate all images' just makes it run on the first one again.

**Comment by PMahern** [comment]
Just pushed up some code:

-  Interrogate All Images should process all images
-  The llama model reference in joycaption app.py should be replaced properly when the repo is cloned
-  Added a system for keeping one python process open for multiple interrogations so hopefully it's faster
- Torch for cuda will be installed on windows systems (although it's still hard coded to cu124 so users will need to have a newer cuda SDK or manually install a torch version that works).
