### ISSUE TITLE
[Feature request] Warning when exiting/changing folder without saving

### ISSUE THREAD

**Issue by DiceOwl** [PMahern/StableDiffusionTagManager#2]
Nice project, but as the title suggests, I recommend a warning message when tags where changed and you quit/change folder. Alternatively, add an option to auto-save the changes after each change. This would help for when the program crashes before saving.

**Comment by PMahern** [comment]
Hi! Thanks for the suggestion, I've developed a habit of chronically hitting save every time I make a change because it this feature was missing. I'll try to get it in the next beta release. You mentioned crashes, have you experienced any and if so were they replicable?

**Comment by PMahern** [comment]
Resolved with [this commit](https://github.com/PMahern/StableDiffusionTagManager/commit/e3e935d294aa97d7e1d5177796f1399bbd7d0304).
