### ISSUE TITLE
RAEDME lacks basic start info

### ISSUE THREAD

**Issue by ppbrown** [PMahern/StableDiffusionTagManager#6]
Hello,
this seems like a useful tool to use.
The README seems to claim that it can be used with or without A1111....
however the "Usage" section doesnt seem to mention how to actually Start The Program.

That needs to be the very first paragraph in any "Usage" documentation!

**Comment by PMahern** [comment]
Updated the readme with some instructions for each supported OS in these commits: https://github.com/PMahern/StableDiffusionTagManager/commit/dca9a9f6d671df9d3d23d03a7c4134cfd7598fa8, https://github.com/PMahern/StableDiffusionTagManager/commit/778b9354ecfc1335fa082568a273bba3df931fb3
