### ISSUE TITLE
Usage feedback

### ISSUE THREAD

**Issue by ppbrown** [PMahern/StableDiffusionTagManager#7]
Hey, thanks for updating the instructions. Now I managed to start it up! looks like it has great potential.
Thought I'd give you my feedback on it. I can open seperate issues on these if you like, but for now, I'll just put everything in this one issue.

My usage case is that I'm using OneTrainer to train loras/models. So my specific need is to generate a .txt file for every image.
I dont see that as an option.

On startup, it prompts me to create a new project. Which sounds potentially useful, with the "default tags" feature etc. But it ALSO says it "backs up a copy of every image".
I dont want that! I just want to do tags!
I really dont want a duplicate copy of all 200 images I have in the directory

The image display is nice.. but it doesnt let me easily do the most basic function; Add A Tag To An Image.
I feel like I should be able to move mouse to the tags area, and either mouseclick, or just press RETURN, to create a new tag. 
That doesnt happen.

When I use the menu  Tags->Add tag to start, it lets me create a tag... but the interface is weird.
Yes it pops up a new tag thingie and I can type in it.
But when I press return.. nothing happens. 
In my opinion, it needs to end input on that tag when I press enter. Right now, its confusing.

**Comment by PMahern** [comment]
I'll make an issue for allowing the user to opt out of image backups. The project feature isn't necessarily something you need to use on every set of images, it's mostly useful if you plan on cropping/editing images. What OS are you using just out of curiosity?

For tag input there's shortcuts to make it faster, they're listed at the bottom of the readme.  Shift + up will add a tag to the front of the tags for the current image. So if you're adding a series of tags to an image you would hit shift + up, "tag1", shift + up, "tag2". You can use shift + left and right to jump around between tags in an image and ctrl + left and right to move the currently focused tag around. You can also drag and drop them after adding a series of them. Once a tag loses focus it should get "committed" to the set. I could also make pressing enter while a tag has focus also drop focus from (thus saving) it if you think that would be more intuitive.

**Comment by PMahern** [comment]
Also I'll add a toolbar button to the tag area for adding a tag since that makes sense there should be a way to do it via mouse click without having to go through the menu (although it would still be fastest to just use the keyboard shortcuts).

**Comment by PMahern** [comment]
The application saves a .txt file for each image, it keeps the current set of tags for each file in memory until you hit save, then it loops over each file, saving a .txt file with the same name with the tags separated by commas (it also reads these text files on startup).

**Comment by ppbrown** [comment]
Reguarding keyboard shortscuts: May i suggest that the menus need to follow the convention of displaying them.
Ie; the current menu item "Add Tag to Start", should read as 
"Add Tag to Start  _^"

also, if i start the program with

"StableDiffusionTagManager ."

it would be nice if it loaded the current directory rather than making me use the File menu.

I'm using Ubuntu Linux by the way

**Comment by PMahern** [comment]
I'll add the shortcuts to the menu items.

**Comment by ppbrown** [comment]
I think you missed what I typed.
I was not saying default to current directory. I was saying if you explicitly give a directory name, go open that directory. And

"."

is the name of your current directory in linux.

**Comment by PMahern** [comment]
Oh sorry, my mistake, yeah that's not a bad suggestion I can add that.

**Comment by PMahern** [comment]
I added the file path argument functionality request as well as the menu shortcuts where appropriate. There's some some functions that have shortcuts that don't have a place to put them because they can't be menu actions, they require focus on the text inputs. Will need to investigate a better way to document. Also added an add tag button to the tag editor toolbar.
