### ISSUE TITLE
Feature request: drag-scroll images

### ISSUE THREAD

**Issue by ppbrown** [PMahern/StableDiffusionTagManager#8]
Its a bit of a pain to have to click on the row of images at the top, then arrow a bunch of times, then click back on the image you want.

Would be nice if you could click-drag the farm-right image showing, to then be the top-left image, and thereby drag the current position of the image parade.

Now that I think of it, a scrollbar wouldnt hurt either.
There is no scrollbar.

This is on Ubuntu Linux, using the precompiled binaries.

**Comment by PMahern** [comment]
Could you try hovering over the bottom of the image list control? I think the default behavior for Avalonia list boxes or maybe something I set hides it unless you hover over where the control would be, I could make it always visible instead. Otherwise it might be a Linux specific thing which I'll have to test. There is also a hotkey to move left and right between images (shift + , or .) that works anywhere in the window. I'll look into reordering image though, would be useful.

**Comment by ppbrown** [comment]
"Image list control"?
no idea what that is. maybe it doesnt even show up in linux

as far as the "shift +" hotkey:

may I suggest that there are WAY too many "shift" things in the interface?
This is not normal. Definitely not convenient.
For one thing: I dont HAVE a "+" key. no numberpad.
And no, (shift -=) which would normally generate a + .. does not work in place of your "shift +".

but why wouldnt you just make left-arrow/right arrow change images??

Please consider the nominal purpose of the program: "managing tags for stable diffusion".

The workflow for that is:

1. start at the first image
2. rapidly type a bunch of tags (autocomplete is very helpful for that, thank you)
3. go to the next image.. REPEAT 100+ times

I just went through 200 images, it was very painful switching between images. Making regular arrow keys go to next/prev image would help a lot. I should never have to switch to my mouse to do this

Also, the whole "SHIFT-enter" thing. Why mandate the shift? and between EVERY tag as well? very annoying and slowing down. :(

Please make it so that when entering tags, Enter ends current tag and starts a new one.

Also make it simpler to say "im done entering tags for this image". May I suggest shift enter or control enter for that one?

**Comment by ppbrown** [comment]
Oh! hey, I just got a glimpse of the scrollbar for images!

for some reason, it is rendering UNDERNEATH the list of images.
Maybe you only use a small amount of images or something, and using it with 200 images makes it not render properly?

**Comment by PMahern** [comment]
Sorry when I say shift + . I mean hold shift and press period and shift + , is hold shift and press comma. It's meant to be like holding shift and then pressing the angle brackets on the keyboard as if they're arrows. 

Can you try hovering your cursor over the line that you're seeing as the scrollbar it should grow larger and then you can drag it, I think it's just the default behavior for list controls (which the control that the images are in) in the Avalonia ui library). Here's a lazy comparison, top is before hovering, bottom is after. I'm sure I can change this behavior so you don't have to hover. If the hover doesn't get it to behave it's probably broken on linux.

![image](https://github.com/PMahern/StableDiffusionTagManager/assets/18010074/be16636a-1317-4bb9-957c-5f3ffda45c36)

**Comment by ppbrown** [comment]
"top is before hovering, bottom is after"

thing is, if I have to stop my mouse and hover.... that slows me down. so itisnt a good workflow.

aha!
it shows up when I FIRST start the prog. but as soon as I switch between images, it gets sent to the background.

I misread what you were saying about keyboard shortcuts. the good news is, I can report that those work for me now.
but.. you could have just said

"<" and ">"

it makes more sense to understand anyway!

but that being said... 
it would be really nice from a new-user perspective if you made left/right arrows do the same thing as well.

**Comment by PMahern** [comment]
Pushed a new release that no longer autohides the scrollbar and displays some shortcuts in the menu options. When you press enter on a tag it will add a new one after the currently focused tag and focus it. I'm not sure what you mean by the "done with an image" functionality, do you mean you want it to advance to the next image? Open a new issue with more specifics, this one is getting a bit broad.
